# Generated by Django 2.0.3 on 2018-05-13 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dns', '0004_auto_20180510_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('interface', models.CharField(max_length=200, unique=True)),
                ('port', models.IntegerField(unique=True)),
                ('proxy_host', models.CharField(max_length=200)),
                ('proxy_exception', models.CharField(max_length=200)),
                ('root_dir', models.CharField(max_length=200)),
                ('dns_challenge', models.BooleanField(default=False)),
                ('ssl_staging', models.BooleanField(default=False)),
                ('dns_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dns_name', to='dns.DNS')),
            ],
        ),
    ]
