# Generated by Django 2.0.3 on 2018-05-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hosts', '0004_host_tls'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='name',
            field=models.CharField(default='primary', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='port',
            field=models.IntegerField(default='80', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='proxy_exception',
            field=models.CharField(default='/assets', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='root_dir',
            field=models.CharField(default='/apps/TygerCaddy/TygerCaddy/', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='config',
            name='proxy_host',
            field=models.CharField(max_length=200),
        ),
    ]
