# Generated by Django 2.0.3 on 2018-05-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hosts', '0005_auto_20180510_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='dns_challenge',
            field=models.BooleanField(default=False),
        ),
    ]
