# Generated by Django 2.0.3 on 2018-05-10 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('dns', '0004_auto_20180510_1648'),
        ('hosts', '0006_config_dns_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='dns_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='dns_name', to='dns.DNS'),
        ),
    ]
