# Generated by Django 2.0.3 on 2018-05-13 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0002_remove_proxy_host'),
        ('hosts', '0008_auto_20180513_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='proxy_host',
        ),
        migrations.AddField(
            model_name='host',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proxies.Proxy'),
        ),
    ]
