# Generated by Django 2.0.3 on 2018-05-28 09:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('hosts', '0012_auto_20180524_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='proxy',
        ),
    ]
