# Generated by Django 2.0.6 on 2018-06-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hosts', '0013_remove_host_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='cert_bundle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='force_redirect_https',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='host',
            name='key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
