# Generated by Django 2.0.6 on 2018-06-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hosts', '0014_auto_20180604_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='custom_ssl',
            field=models.BooleanField(default=False),
        ),
    ]
