# Generated by Django 2.0.6 on 2018-06-09 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('hosts', '0015_host_custom_ssl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='cert_bundle',
        ),
        migrations.RemoveField(
            model_name='host',
            name='custom_ssl',
        ),
        migrations.RemoveField(
            model_name='host',
            name='key',
        ),
    ]
