# Generated by Django 2.0.6 on 2018-06-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('certificates', '0002_remove_certificate_host'),
        ('hosts', '0016_auto_20180609_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='custom_certs',
            field=models.ManyToManyField(to='certificates.Certificate'),
        ),
        migrations.AddField(
            model_name='host',
            name='custom_ssl',
            field=models.BooleanField(default=False),
        ),
    ]
