# Generated by Django 2.0.6 on 2018-08-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hosts', '0017_auto_20180609_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='basic_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='basic_password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='basic_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='custom_certs',
            field=models.ManyToManyField(blank=True, to='certificates.Certificate'),
        ),
    ]
