# Generated by Django 2.0.6 on 2018-06-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('hosts', '0016_auto_20180609_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_name', models.CharField(max_length=200, unique=True)),
                ('bundle_upload', models.FileField(blank=True, null=True, upload_to='')),
                ('key_upload', models.FileField(blank=True, null=True, upload_to='')),
                ('bundle_text', models.TextField(blank=True, max_length=500, null=True)),
                ('key_text', models.TextField(blank=True, max_length=500, null=True)),
                ('host', models.ManyToManyField(to='hosts.Host')),
            ],
        ),
    ]
