# Generated by Django 2.0.6 on 2018-06-09 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='host',
        ),
    ]
