# Generated by Django 2.0.6 on 2018-06-09 12:18

import certificates.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('certificates', '0002_remove_certificate_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_file', models.FileField(upload_to=certificates.models.get_cert_path)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_file', models.FileField(upload_to=certificates.models.get_cert_path)),
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='bundle_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='certificates.Bundle'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='key_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='certificates.Key'),
        ),
    ]
