# Generated by Django 2.0.6 on 2018-06-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_auto_20180609_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='bundle_text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='key_text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
