# Generated by Django 2.0.3 on 2018-05-13 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0008_auto_20180513_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('upstream', models.BooleanField(default=False)),
                ('downstream', models.BooleanField(default=False)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_from', models.CharField(default='/', max_length=255)),
                ('proxy_to', models.CharField(max_length=255)),
                ('fail_timeout', models.IntegerField(blank=True)),
                ('max_fails', models.IntegerField(blank=True)),
                ('max_conns', models.IntegerField(blank=True)),
                ('try_duration', models.IntegerField(blank=True)),
                ('try_interval', models.IntegerField(blank=True)),
                ('health_check', models.CharField(blank=True, max_length=255)),
                ('health_check_port', models.CharField(blank=True, max_length=255)),
                ('health_check_interval', models.IntegerField(blank=True)),
                ('health_check_timeout', models.IntegerField(blank=True)),
                ('keep_alive', models.IntegerField(blank=True)),
                ('timeout', models.IntegerField(blank=True)),
                ('without', models.CharField(blank=True, max_length=255)),
                ('exceptions', models.CharField(blank=True, max_length=255)),
                ('insecure_skip_verify', models.BooleanField(default=False)),
                ('websocket', models.BooleanField(default=False)),
                ('transparent', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.Host')),
                ('load_policy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='proxies.Policies')),
            ],
        ),
        migrations.AddField(
            model_name='headers',
            name='proxy',
            field=models.ManyToManyField(to='proxies.Proxy'),
        ),
    ]
