# Generated by Django 2.0.3 on 2018-05-13 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0003_proxy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='exceptions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='fail_timeout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='health_check',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='health_check_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='health_check_port',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='health_check_timeout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='keep_alive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='load_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proxies.Policies'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='max_conns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='max_fails',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='timeout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='try_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='try_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='without',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
