# Generated by Django 2.0.3 on 2018-05-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0004_auto_20180513_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255, unique=True)),
                ('upstream', models.BooleanField(default=False)),
                ('downstream', models.BooleanField(default=False)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='headers',
            name='proxy',
        ),
        migrations.AlterField(
            model_name='proxy',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Headers',
        ),
        migrations.AddField(
            model_name='header',
            name='proxy',
            field=models.ManyToManyField(to='proxies.Proxy'),
        ),
    ]
