# Generated by Django 2.0.3 on 2018-05-14 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0005_auto_20180513_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='proxy',
        ),
        migrations.AddField(
            model_name='header',
            name='proxy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proxies.Proxy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proxy',
            name='health_check_interval',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='health_check_timeout',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='timeout',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
