# Generated by Django 2.0.3 on 2018-05-28 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hosts', '0013_remove_host_proxy'),
        ('proxies', '0006_auto_20180514_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='hosts.Host'),
        ),
    ]
