# Generated by Django 2.0.3 on 2018-05-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evariables',
            name='variable',
            field=models.CharField(max_length=200),
        ),
    ]
