# Generated by Django 2.0.3 on 2018-05-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dns', '0002_auto_20180510_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='evariables',
            name='value',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
